;;; init.el --- my init.el           -*- lexical-binding: t; -*-
;;; Commentary:
;;; Code:
(setq custom-file (locate-user-emacs-file "custom.el"))
(require 'package)
(setq package-enable-at-startup nil)
(setq
 package-archives
 '(("melpa"        . "http://melpa.org/packages/")
   ("melpa-stable" . "https://stable.melpa.org/packages/")
   ("org"          . "http://orgmode.org/elpa/")
   ("gnu"          . "http://elpa.gnu.org/packages/")))

;; (eval-when-compile
;; (when (boundp 'package-pinned-packages)
;;   (setq package-pinned-packages
;;         '((evil      . "melpa-stable")))))
(package-initialize)

(add-to-list 'load-path "~/.emacs.d/mylisp")
(require 'mymacros)
(add-to-list 'load-path "~/.emacs.d/inits")
(require '00-init)
(require '01-graphics)
(require '02-exec-path-from-shell)
(require '10-evil)
(require '10-ivy)
(require '10-shackle)
(require '10-winner)
(require '10-which-key)
(require '10-hl-todo)
(require '10-smart-mode-line)
;; (require '10-ripgrep)
(require '20-eshell)
(require '20-ddskk)
;; (require '20-migemo)
(require '20-company)
(require '20-yasnippet)
(require '20-flycheck)
(require '20-smartparens)
(require '20-rainbow-delimiters)
(require '20-highlight-indent-guides)
(require '20-magit)
(require '30-emacslisp)
;; (require '30-bison)
;; (require '30-cmake)
(require '30-latex)
(require '30-org)
(require '30-yaml)
(require '30-common-lisp)
(require '30-agda)
(require '30-ocaml)
(require '30-fsharp)
(require '30-markdown)
(require '30-coq)
(require '30-lean)
(require '31-lsp)
(require '32-c++)
(require '32-rust)
(require '32-haskell)

(install-when-compile 'package-utils)
(provide 'init)
;;; init.el ends here
